import { useState } from 'react'
import { ArrowUp, BookOpen, Check, Copy, Menu, Moon, ShieldCheck, Sun } from 'lucide-react'

const nav = [['overview','Overview'],['information','Information handled'],['use','How it is used'],['services','Third-party services'],['storage','Storage & retention'],['sharing','Sharing'],['security','Security'],['children','Children'],['choices','Your choices'],['changes','Policy changes'],['contact','Contact']]
function App() {
  const [dark,setDark] = useState(false), [open,setOpen] = useState(false), [copied,setCopied] = useState(false)
  const copy = async () => { try { await navigator.clipboard.writeText('business.gursharn@gmail.com'); setCopied(true); window.setTimeout(()=>setCopied(false),1600) } catch { window.location.href='mailto:business.gursharn@gmail.com' } }
  return <div className={dark?'app dark':'app'} id="top">
    <header className="bar"><a className="brand" href="#top"><span className="mark"><BookOpen size={19}/></span>NitPath<span className="gold">.</span></a>
      <nav className={open?'nav show':'nav'}>{nav.slice(0,3).map(([id,label])=><a key={id} href={'#'+id} onClick={()=>setOpen(false)}>{label}</a>)}</nav>
      <div className="actions"><button className="round" onClick={()=>setDark(!dark)} aria-label="Toggle theme">{dark?<Sun size={17}/>:<Moon size={17}/>}</button><button className="round mobile" onClick={()=>setOpen(!open)} aria-label="Toggle navigation"><Menu size={18}/></button><a className="support" href="mailto:business.gursharn@gmail.com">Contact support ↗</a></div>
    </header>
    <section className="hero"><div className="hero-inner"><div className="eyebrow"><ShieldCheck size={14}/> TRANSPARENCY & TRUST</div><div className="hero-grid"><div><h1>Your privacy,<br/><i>held with care.</i></h1><p className="lead">A clear guide to the information NitPath handles when you read, explore, and engage with Gurbani and Nitnem.</p><div className="meta"><span>● Privacy policy</span><b>·</b> For the NitPath Android app</div></div><div className="hero-card"><span className="hero-icon"><BookOpen size={22}/></span><small>NITPATH · ANDROID</small><h2>A mindful reading space.</h2><p>Designed for a focused and personal scripture-reading experience.</p><hr/><div className="pkg"><span>Package</span><code>com.nitpath.app</code></div></div></div></div></section>
    <main className="layout"><aside className="toc"><small>ON THIS PAGE</small>{nav.map(([id,label],i)=><a key={id} href={'#'+id}><em>{String(i+1).padStart(2,'0')}</em>{label}</a>)}<div className="aside-note"><ShieldCheck size={16}/> Written to explain our data practices in plain language.</div></aside>
    <article className="policy">
      <section className="intro" id="overview"><small className="kicker">PRIVACY POLICY</small><h2>About this policy</h2><p>This policy describes how the NitPath Android app handles information when you use its features. It is written to be clear and practical. It must be checked against the exact app version and enabled services before publication.</p><div className="facts"><div><small>Publisher</small><strong>Gursharn Singh</strong></div><div><small>App</small><strong>NitPath</strong></div><div><small>Effective date</small><strong className="pending">Set before publication</strong></div></div></section>
      <section className="section" id="information"><small className="kicker">01 / DATA</small><h2>Information the app handles</h2><p>NitPath may store information on your device to provide reading and personalization features. Whether information is also transmitted off-device depends on the app's actual behavior and enabled third-party services.</p><div className="cards"><div className="info-card"><span className="ico green"><BookOpen size={18}/></span><h3>Reading activity</h3><p>Reading progress, completion records, bookmarks, and optional bookmark notes may be stored locally.</p></div><div className="info-card"><span className="ico tan"><Sun size={18}/></span><h3>Preferences</h3><p>Theme, font size, layout, and language display preferences may be saved on your device.</p></div><div className="info-card"><span className="ico blue"><ShieldCheck size={18}/></span><h3>App content</h3><p>Scripture files, downloaded content, and cached Hukamnama information may be stored for reading and offline access.</p></div></div><div className="caution"><b>Important:</b> These categories reflect development review, not a final guarantee. Confirm the release implementation, backup behavior, and SDK collection before publication.</div></section>
      <section className="section" id="use"><small className="kicker">02 / PURPOSE</small><h2>How information is used</h2><p>Information stored by NitPath supports app functionality, including:</p><ul className="checks"><li><Check/> Remembering reading progress and preferences.</li><li><Check/> Saving bookmarks and associated notes.</li><li><Check/> Displaying downloaded or cached scripture content.</li><li><Check/> Supporting online content retrieval when a network connection is needed.</li></ul><p>Any analytics, diagnostics, or secondary uses must be described only after they are confirmed in the final build.</p></section>
      <section className="section" id="services"><small className="kicker">03 / PROVIDERS</small><h2>Third-party services</h2><p>NitPath may connect to external services to retrieve content or support functionality. Network requests can expose technical information, such as an IP address and request metadata, to the receiving service. Exact handling depends on the provider and its terms.</p><div className="providers">{[['BaniDB','Scripture/content service'],['GurbaniNow','Content service'],['GitHub-hosted content','Raw content hosting'],['Google Firebase Analytics','Previously reported unlinked; final SDK/runtime status not confirmed']].map(([name,desc])=><div className="provider" key={name}><div><b>{name}</b><span>{desc}</span></div><small>Review pending</small></div>)}</div><p>Review current provider privacy terms and the final app configuration before relying on these descriptions. Unlinking an integration alone does not prove an SDK is absent or that no data is collected.</p></section>
      <section className="section" id="storage"><small className="kicker">04 / RETENTION</small><h2>Storage and retention</h2><p>The intended local-data retention approach is to keep app data until you delete it or uninstall NitPath. This may include reading progress, preferences, bookmarks, notes, and cached or downloaded content, depending on the feature and implementation.</p><div className="notice"><ShieldCheck/><div><b>Android backup is still being verified</b><p>Android or device backup settings may affect whether app data is restored or retained outside the app installation. Do not assume uninstalling removes every backup copy. Finalize this statement after checking the release backup and data-extraction rules.</p></div></div></section>
      <section className="section" id="sharing"><small className="kicker">05 / DISCLOSURE</small><h2>Sharing and disclosure</h2><p>When NitPath requests online content, information needed to make the request is transmitted to the relevant service. If analytics or other SDKs are enabled, they may transmit additional information according to their configuration and provider terms.</p><p>The final release's data flows must be verified before making definitive statements about sharing, sale, or disclosure. This draft does not claim that no information is shared.</p></section>
      <section className="section" id="security"><small className="kicker">06 / SAFEGUARDS</small><h2>Security</h2><p>NitPath uses HTTPS for reviewed network connections, which helps protect information in transit. No method of transmission or storage is completely secure, and available protections depend on the app, device, operating system, and service providers.</p><p>Security statements should be checked against the final release configuration and actual data flows.</p></section>
      <section className="section" id="children"><small className="kicker">07 / AUDIENCE</small><h2>Children and audience</h2><p>NitPath is intended for a mixed audience that may include children and adults. The developer must confirm the precise target age groups in Google Play Console and ensure the app, SDKs, and data practices meet applicable requirements, including Google Play Families policies where relevant.</p><p>Before publication, verify whether analytics or other third-party SDKs collect information from children or users of unknown age, and configure or remove services as needed. This policy does not claim a legal or policy-compliance determination.</p></section>
      <section className="section" id="choices"><small className="kicker">08 / CONTROL</small><h2>Your choices and deletion</h2><p>You can use available app controls to manage information such as bookmarks or preferences, where those controls are provided. A single in-app “delete all local data” feature has not been confirmed.</p><p>For privacy questions or requests, contact the developer using the email below. The ability to locate or delete information held by third-party services or device backups may depend on those services and verified app data practices.</p></section>
      <section className="section" id="changes"><small className="kicker">09 / UPDATES</small><h2>Changes to this policy</h2><p>This policy may be updated when NitPath's features, data handling, service providers, or applicable requirements change. The published version should show an accurate effective or last-updated date. Please review this page periodically for changes.</p></section>
      <section className="contact" id="contact"><span className="contact-icon"><ShieldCheck size={21}/></span><div><small className="kicker">10 / CONTACT</small><h2>Questions about privacy?</h2><p>For questions about this policy or NitPath's privacy practices, contact the publisher.</p><b>Gursharn Singh</b><span>NitPath · Android app</span><div className="email"><a href="mailto:business.gursharn@gmail.com">business.gursharn@gmail.com</a><button onClick={copy}>{copied?<Check size={14}/>:<Copy size={14}/>} {copied?'Copied':'Copy'}</button></div></div></section>
      <div className="publish-note"><b>Publication note:</b> This is a draft until the effective date, Firebase status, backup behavior, provider terms, deletion controls, and child-audience requirements have been verified and finalized. Resolve all outstanding items and remove this note before using the page as the public Google Play privacy policy.</div>
    </article></main>
    <footer className="footer"><a className="brand" href="#top"><span className="mark"><BookOpen size={16}/></span>NitPath<span className="gold">.</span></a><span>Privacy Policy · Gursharn Singh</span><a href="#top">Back to top <ArrowUp size={14}/></a></footer>
  </div>
}
export default App
